source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '9.0'
use_frameworks!

target 'SecureBook-ObjC' do
# Networking
pod 'AFNetworking', '~> 3.0'

# Easy CoreData
pod 'MagicalRecord'

# AES 256 CBC
#pod 'RNCryptor', '~> 4.0.0-beta'

# Notifications
pod 'Mercury'

# Nice Pull to refresh
pod 'DGElasticPullToRefresh'
end

target 'SecureBook-ObjCTests' do

end

target 'SecureBook-ObjCUITests' do

end